In [69]:
import math
from typing import Optional

import torch
import torch.nn as nn

In [9]:
emb = nn.Embedding(num_embeddings=5, embedding_dim=3)
emb

Embedding(5, 3)

In [10]:
dir(emb)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_fill_padding_idx_with_zero',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules

In [15]:
print(emb.padding_idx)
print(emb.weight)

None
Parameter containing:
tensor([[ 0.8124, -0.5914,  1.0241],
        [ 0.5375, -0.7507,  0.2593],
        [-2.0287, -1.6452,  1.5384],
        [-0.5805, -0.5312,  1.0031],
        [ 0.8015, -2.1029,  0.2422]], requires_grad=True)


In [25]:
print(torch.tensor([0]).dtype)
print(torch.Tensor([0]).dtype)

torch.int64
torch.float32


In [26]:
print(emb(torch.tensor([0])))

tensor([[ 0.8124, -0.5914,  1.0241]], grad_fn=<EmbeddingBackward0>)


In [37]:
### 1. W 만들기
# [Vocab_size, dim]
vocab_size, dim = 100, 256
W = torch.randn(vocab_size, dim, requires_grad=True)
print(W.shape)

### 2. 동작 과정
# 2-1. 인덱스 k. 단어 0~99 중 5번째 index
k = 5
# 2-2. one-hot vector로 변환
k_vector = torch.zeros(vocab_size)
k_vector[k] = 1
print(k_vector)
print(k_vector.shape)
k_vector = k_vector.unsqueeze(0)
print(k_vector.shape)

# 2-3. 행렬곱으로 W_5의 행만 추출
torch.matmul(k_vector, W)


torch.Size([100, 256])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([100])
torch.Size([1, 100])


tensor([[-3.0722e-02,  3.4651e-01, -1.6014e+00,  1.1328e+00,  3.7816e-01,
         -1.9764e+00,  6.8071e-01, -3.7107e-01,  1.3613e+00,  2.1737e+00,
          2.2640e+00,  1.1904e+00, -1.8112e+00,  1.4188e+00, -6.9237e-01,
          4.5711e-01,  6.6513e-01, -6.5726e-01,  1.1107e+00,  1.0151e+00,
         -1.3071e+00,  9.1559e-01,  1.2806e-01,  3.1776e-01,  9.5807e-01,
         -1.8630e+00,  1.0862e+00,  1.0757e-01, -2.1369e+00, -1.3925e-01,
          5.9510e-01, -2.0587e-01,  1.1864e+00,  1.4223e+00,  1.9868e-01,
          7.1203e-01,  1.2306e+00,  6.2350e-05,  7.0175e-01,  1.9119e+00,
          1.6196e+00, -1.6134e-01,  4.3097e-01, -2.8825e-01,  2.0788e-01,
         -1.1368e+00, -9.2631e-01,  1.5338e-01,  1.6220e+00,  9.2390e-01,
         -1.9136e+00,  1.1105e-01, -1.2947e+00,  3.7382e-01, -6.8803e-01,
          1.1713e+00,  1.8557e+00,  1.9943e-01,  5.5493e-01,  1.3390e+00,
         -1.0884e+00,  1.6349e+00, -9.2087e-01,  1.6598e+00, -4.1417e-01,
          1.6856e+00, -8.0029e-01, -2.

In [43]:
k_vector = torch.nn.functional.one_hot(torch.tensor([k]), num_classes=vocab_size)
print(k_vector.dtype)
k_vector = k_vector.float()

print(torch.matmul(k_vector, W))

torch.int64
tensor([[-3.0722e-02,  3.4651e-01, -1.6014e+00,  1.1328e+00,  3.7816e-01,
         -1.9764e+00,  6.8071e-01, -3.7107e-01,  1.3613e+00,  2.1737e+00,
          2.2640e+00,  1.1904e+00, -1.8112e+00,  1.4188e+00, -6.9237e-01,
          4.5711e-01,  6.6513e-01, -6.5726e-01,  1.1107e+00,  1.0151e+00,
         -1.3071e+00,  9.1559e-01,  1.2806e-01,  3.1776e-01,  9.5807e-01,
         -1.8630e+00,  1.0862e+00,  1.0757e-01, -2.1369e+00, -1.3925e-01,
          5.9510e-01, -2.0587e-01,  1.1864e+00,  1.4223e+00,  1.9868e-01,
          7.1203e-01,  1.2306e+00,  6.2350e-05,  7.0175e-01,  1.9119e+00,
          1.6196e+00, -1.6134e-01,  4.3097e-01, -2.8825e-01,  2.0788e-01,
         -1.1368e+00, -9.2631e-01,  1.5338e-01,  1.6220e+00,  9.2390e-01,
         -1.9136e+00,  1.1105e-01, -1.2947e+00,  3.7382e-01, -6.8803e-01,
          1.1713e+00,  1.8557e+00,  1.9943e-01,  5.5493e-01,  1.3390e+00,
         -1.0884e+00,  1.6349e+00, -9.2087e-01,  1.6598e+00, -4.1417e-01,
          1.6856e+00, -8.0

In [44]:
W[k]

tensor([-3.0722e-02,  3.4651e-01, -1.6014e+00,  1.1328e+00,  3.7816e-01,
        -1.9764e+00,  6.8071e-01, -3.7107e-01,  1.3613e+00,  2.1737e+00,
         2.2640e+00,  1.1904e+00, -1.8112e+00,  1.4188e+00, -6.9237e-01,
         4.5711e-01,  6.6513e-01, -6.5726e-01,  1.1107e+00,  1.0151e+00,
        -1.3071e+00,  9.1559e-01,  1.2806e-01,  3.1776e-01,  9.5807e-01,
        -1.8630e+00,  1.0862e+00,  1.0757e-01, -2.1369e+00, -1.3925e-01,
         5.9510e-01, -2.0587e-01,  1.1864e+00,  1.4223e+00,  1.9868e-01,
         7.1203e-01,  1.2306e+00,  6.2350e-05,  7.0175e-01,  1.9119e+00,
         1.6196e+00, -1.6134e-01,  4.3097e-01, -2.8825e-01,  2.0788e-01,
        -1.1368e+00, -9.2631e-01,  1.5338e-01,  1.6220e+00,  9.2390e-01,
        -1.9136e+00,  1.1105e-01, -1.2947e+00,  3.7382e-01, -6.8803e-01,
         1.1713e+00,  1.8557e+00,  1.9943e-01,  5.5493e-01,  1.3390e+00,
        -1.0884e+00,  1.6349e+00, -9.2087e-01,  1.6598e+00, -4.1417e-01,
         1.6856e+00, -8.0029e-01, -2.0695e+00, -2.2

In [49]:
### 차원 확장
# [L]
ids = torch.tensor([5, 2, 5, 99], dtype=torch.long)
print(ids.shape)
print(W[ids].shape)
print(W[ids])

torch.Size([4])
torch.Size([4, 256])
tensor([[-0.0307,  0.3465, -1.6014,  ..., -0.2560, -1.0969, -0.7485],
        [-0.4187,  1.2387,  0.3733,  ...,  1.2210,  0.3334,  0.6010],
        [-0.0307,  0.3465, -1.6014,  ..., -0.2560, -1.0969, -0.7485],
        [-1.0016,  1.0505, -1.5956,  ..., -0.7479,  1.1884,  1.4126]],
       grad_fn=<IndexBackward0>)


In [61]:
ids = torch.tensor([5, 2, 5, 99], dtype=torch.long)
one_hot_ids = torch.nn.functional.one_hot(ids, num_classes=vocab_size).to(W.dtype)
print(one_hot_ids.shape)

torch.matmul(one_hot_ids, W)

torch.Size([4, 100])


tensor([[-0.0307,  0.3465, -1.6014,  ..., -0.2560, -1.0969, -0.7485],
        [-0.4187,  1.2387,  0.3733,  ...,  1.2210,  0.3334,  0.6010],
        [-0.0307,  0.3465, -1.6014,  ..., -0.2560, -1.0969, -0.7485],
        [-1.0016,  1.0505, -1.5956,  ..., -0.7479,  1.1884,  1.4126]],
       grad_fn=<MmBackward0>)

In [54]:
# [B, L]
B, L = 2, 4
ids = torch.randint(0, vocab_size, (B,L), dtype=torch.long)
print(ids.shape)
print(W[ids].shape)
print(W[ids])

torch.Size([2, 4])
torch.Size([2, 4, 256])
tensor([[[-0.2622, -0.0513, -1.0129,  ...,  1.9487, -0.0412, -0.9401],
         [ 0.6715, -0.3268,  0.2919,  ...,  0.4442, -0.9443, -1.4110],
         [-0.5745,  0.0285,  0.6114,  ..., -0.3304, -0.0023,  1.7851],
         [-1.3889, -1.8623,  0.5936,  ...,  0.0299,  0.4371,  0.6816]],

        [[ 1.4983,  0.9322, -0.1769,  ..., -0.6162,  0.5138,  0.6981],
         [ 0.4030, -1.0858, -0.8338,  ...,  0.1925, -0.9338,  1.1017],
         [-0.7258,  1.9101,  0.7005,  ...,  0.7185,  1.5096,  0.3996],
         [ 1.4983,  0.9322, -0.1769,  ..., -0.6162,  0.5138,  0.6981]]],
       grad_fn=<IndexBackward0>)


In [67]:
w = torch.randn(3,3) / math.sqrt(3)
w.requires_grad = True
print(w.is_leaf)

w = w.to('mps')
print(w.is_leaf)

loss = (w**2).sum()
loss.backward()
print(w.grad)


True
False
None


/var/folders/56/h6vkkmvd0zzcr59jvcgzr4y40000gn/T/ipykernel_20850/938295077.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:497.)
  print(w.grad)


In [114]:
class Embedding:
    def __init__(
        self,
        num_embeddings: int,
        embedding_dim: int,
        padding_idx: Optional[int] = None,
    ):
        if padding_idx is not None:
            if not (0 <= padding_idx < num_embeddings):
                raise ValueError("padding_idx must be in [0, num_embeddings)")
        self.num_embeddings = num_embeddings
        self.embedding_dim = embedding_dim
        self.padding_idx = padding_idx
        self.training = True

        self.scale = math.sqrt(embedding_dim)
        self.weight = torch.randn(num_embeddings, embedding_dim) / self.scale
        self.weight.requires_grad_()

        if self.padding_idx is not None:
            with torch.no_grad():
                self.weight[self.padding_idx].zero_()

    def __call__(self, x: torch.Tensor) -> torch.Tensor:
        return self.forward(x)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # [B,L] -> [B,L,embedding_dim]
        return self.weight[x]

    def parameters(self):
        return [self.weight]
    
    def train(self, mode: bool = True):
        self.training = mode
        return self
    
    def eval(self):
        return self.train(False)

    def to(self, device: torch.device):
        self.weight = self.weight.to(device).detach().requires_grad_(True)
        return self
    
    def zero_grad(self):
        if self.weight.grad is not None:
            self.weight.grad.zero_()

In [115]:
### Test
my_emb = Embedding(
    num_embeddings=100,
    embedding_dim=64,
    padding_idx = 0
)

my_input_ids = torch.tensor([[1, 52, 73, 0]]) 
my_output = my_emb(my_input_ids)

print(my_input_ids.shape)
print(my_output.shape)
print(my_output[0,3].sum().item())

emb = nn.Embedding(
    num_embeddings=100,
    embedding_dim=64,
    padding_idx = 0
)

input_ids = torch.tensor([[1, 52, 73, 0]]) 
output = emb(input_ids)

print(input_ids.shape)
print(output.shape)
print(output[0,3].sum().item())

torch.Size([1, 4])
torch.Size([1, 4, 64])
0.0
torch.Size([1, 4])
torch.Size([1, 4, 64])
0.0


In [116]:
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print("device:", device)

device: mps


In [117]:
torch.manual_seed(0)

my_emb = Embedding(num_embeddings=100, embedding_dim=64, padding_idx=0).to(device)
nn_emb = nn.Embedding(num_embeddings=100, embedding_dim=64, padding_idx=0).to(device)

ids = torch.tensor([[1, 52, 73, 0]], dtype=torch.long, device=device)

y_my = my_emb(ids)
y_nn = nn_emb(ids)

loss_my = y_my.sum()
loss_nn = y_nn.sum()

my_emb.zero_grad()
nn_emb.weight.grad = None 

loss_my.backward()
loss_nn.backward()

print("[my] grad exists:", my_emb.weight.grad is not None)
print("[nn] grad exists:", nn_emb.weight.grad is not None)

print("[my] grad shape:", my_emb.weight.grad.shape)
print("[nn] grad shape:", nn_emb.weight.grad.shape)

my_nonzero_rows = (my_emb.weight.grad.abs().sum(dim=1) != 0).nonzero().flatten()
nn_nonzero_rows = (nn_emb.weight.grad.abs().sum(dim=1) != 0).nonzero().flatten()

print("[my] nonzero grad rows:", my_nonzero_rows[:20].tolist())
print("[nn] nonzero grad rows:", nn_nonzero_rows[:20].tolist())

[my] grad exists: True
[nn] grad exists: True
[my] grad shape: torch.Size([100, 64])
[nn] grad shape: torch.Size([100, 64])
[my] nonzero grad rows: [0, 1, 52, 73]
[nn] nonzero grad rows: [0, 1, 52, 73]


In [118]:
lr = 0.1

my_pad_before = my_emb.weight[0].detach().clone()
nn_pad_before = nn_emb.weight[0].detach().clone()

with torch.no_grad():
    my_emb.weight -= lr * my_emb.weight.grad
    nn_emb.weight -= lr * nn_emb.weight.grad

my_pad_after = my_emb.weight[0].detach().clone()
nn_pad_after = nn_emb.weight[0].detach().clone()

print("[my] pad changed:", not torch.allclose(my_pad_before, my_pad_after))
print("[nn] pad changed:", not torch.allclose(nn_pad_before, nn_pad_after))

print("[my] pad row sum after:", my_emb.weight[0].sum().item())
print("[nn] pad row sum after:", nn_emb.weight[0].sum().item())

[my] pad changed: True
[nn] pad changed: True
[my] pad row sum after: -6.400000095367432
[nn] pad row sum after: -6.400000095367432
